loucloud/host/models.py
#!/usr/bin/env python
# encoding: utf-8


from sqlalchemy import Column
from ..extensions import db
from .constants import HOST_OK

class Host(db.Model):

    __tablename__ = 'hosts'

    id = Column(db.Integer, primary_key=True)
    name = Column(db.String(128), nullable=False, unique=True)
    username = Column(db.String(32), default="shiyanlou")
    password = Column(db.String(32), default="shiyanlou")
    status_code = Column(db.SmallInteger, default=HOST_OK)

loucloud/image/models.py
#!/usr/bin/env python
# encoding: utf-8


from sqlalchemy import Column
from ..extensions import db
# from .constants import HOST_OK

class Host(db.Model):

    __tablename__ = 'images'

    image_name = Column(db.String(128), primary_key=True)
    image_path = COlumn(db.String(256), nullable=False)
    

loucloud/template/models.py
#!/usr/bin/env python
# encoding: utf-8


from sqlalchemy import Column
from ..extensions import db
# from .constants import HOST_OK

# class Host(db.Model):

#     __tablename__ = 'hosts'

#     id = Column(db.Integer, primary_key=True)
#     name = Column(db.String(128), nullable=False, unique=True)
#     username = Column(db.String(32), default="shiyanlou")
#     password = Column(db.String(32), default="shiyanlou")
#     status_code = Column(db.SmallInteger, default=HOST_OK)

loucloud/user/models.py
#!/usr/bin/env python
# encoding: utf-8

from sqlalchemy import Column
from ..extensions import db
from .constants import USER_NORMAL, USER_ADMIN
from werkzeug import generate_password_hash, check_password_hash
from flask.ext.login import UserMixin

class User(db.Model, UserMixin):

    __tablename__ = 'users'

    id = Column(db.Integer, primary_key=True)
    name = Column(db.String(128), nullable=False, unique=True)
    _password = Column('password', db.String(256), nullable=False)
    def _get_password(self):
        return self._password

    def _set_password(self, password):
        self._password = generate_password_hash(password)
    # Hide password encryption by exposing password field only.
    password = db.synonym('_password',
                          descriptor=property(_get_password,
                                              _set_password))

    def check_password(self, password):
        if self.password is None:
            return False
        return check_password_hash(self.password, password)
        
        
    type_code = Column(db.SmallInteger, default=USER_NORMAL)
    
    def is_admin(self):
        return self.type_code == USER_ADMIN
        
    @classmethod
    def authenticate(cls, login, password):
        user = cls.query.filter(User.name == login).first()

        if user:
            authenticated = user.check_password(password)
        else:
            authenticated = False

        return user, authenticated

loucloud/vm/models.py
#!/usr/bin/env python
# encoding: utf-8


from sqlalchemy import Column
from ..extensions import db
from .constants import HOST_OK

class Host(db.Model):

    __tablename__ = 'hosts'

    id = Column(db.Integer, primary_key=True)
    name = Column(db.String(128), nullable=False, unique=True)
    username = Column(db.String(32), default="shiyanlou")
    password = Column(db.String(32), default="shiyanlou")
    status_code = Column(db.SmallInteger, default=HOST_OK)

loucloud/frontend/forms.py
#!/usr/bin/env python
# encoding: utf-8

from flask_wtf import Form
from wtforms import (TextField, SubmitField, HiddenField, PasswordField)
from wtforms.validators import Required, Length

class LoginForm(Form):
    next = HiddenField()
    login = TextField(u'Username', [Required()])
    password = PasswordField('Password', [Required(), Length(6, 12)])
    submit = SubmitField('Login')

loucloud/host/forms.py
#!/usr/bin/env python
# encoding: utf-8

from flask_wtf import Form
from wtforms import TextField, SubmitField, IntegerField, SelectField
from .constants import HOST_STATUS, HOST_OK
from wtforms.validators import Required, AnyOf

class AddHostForm(Form):
    name = TextField(u'Hostname', [Required()])
    username = TextField(u'Username', [Required()])
    password = TextField(u'Password', [Required()])
    status_code = SelectField(
        u'StatusCode',
        [AnyOf([str(val) for val in HOST_STATUS.keys()])],
        choices=[(str(val), label) for val, label in HOST_STATUS.items()],
        default=HOST_OK)

    submit = SubmitField(u'Add')

loucloud/image/forms.py
#!/usr/bin/env python
# encoding: utf-8

# from flask_wtf import Form
# from wtforms import TextField, SubmitField, IntegerField, SelectField
# from .constants import HOST_STATUS, HOST_OK
# from wtforms.validators import Required, AnyOf

# class AddHostForm(Form):
#     name = TextField(u'Hostname', [Required()])
#     username = TextField(u'Username', [Required()])
#     password = TextField(u'Password', [Required()])
#     status_code = SelectField(
#         u'StatusCode',
#         [AnyOf([str(val) for val in HOST_STATUS.keys()])],
#         choices=[(str(val), label) for val, label in HOST_STATUS.items()],
#         default=HOST_OK)

#     submit = SubmitField(u'Add')

loucloud/template/forms.py
#!/usr/bin/env python
# encoding: utf-8

# from flask_wtf import Form
# from wtforms import TextField, SubmitField, IntegerField, SelectField
# from .constants import HOST_STATUS, HOST_OK
# from wtforms.validators import Required, AnyOf

# class AddHostForm(Form):
#     name = TextField(u'Hostname', [Required()])
#     username = TextField(u'Username', [Required()])
#     password = TextField(u'Password', [Required()])
#     status_code = SelectField(
#         u'StatusCode',
#         [AnyOf([str(val) for val in HOST_STATUS.keys()])],
#         choices=[(str(val), label) for val, label in HOST_STATUS.items()],
#         default=HOST_OK)

#     submit = SubmitField(u'Add')

loucloud/user/forms.py
#!/usr/bin/env python
# encoding: utf-8

loucloud/vm/forms.py
#!/usr/bin/env python
# encoding: utf-8

# from flask_wtf import Form
# from wtforms import TextField, SubmitField, IntegerField, SelectField
# from .constants import HOST_STATUS, HOST_OK
# from wtforms.validators import Required, AnyOf

# class AddHostForm(Form):
#     name = TextField(u'Hostname', [Required()])
#     username = TextField(u'Username', [Required()])
#     password = TextField(u'Password', [Required()])
#     status_code = SelectField(
#         u'StatusCode',
#         [AnyOf([str(val) for val in HOST_STATUS.keys()])],
#         choices=[(str(val), label) for val, label in HOST_STATUS.items()],
#         default=HOST_OK)

#     submit = SubmitField(u'Add')

loucloud/__init__.py
#!/usr/bin/env python
# encoding: utf-8

from .host import host
from .flask_app import app
from .extensions import db

loucloud/frontend/__init__.py
#!/usr/bin/env python
# encoding: utf-8

from .views import frontend

loucloud/frontend/views.py
#!/usr/bin/env python
# encoding: utf-8

from flask import (Blueprint, render_template, current_app, request,
                   flash, url_for, redirect, session, abort)
from flask.ext.login import login_required, login_user, current_user, logout_user, confirm_login, login_fresh

from .forms import LoginForm
from ..user import User

frontend = Blueprint('frontend', __name__)

@frontend.route('/', methods=['GET'])
def index():
    return redirect(url_for('user.index'))

@frontend.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated():
        return redirect(url_for('user.index'))

    form = LoginForm(login=request.args.get('login', None),
                     next=request.args.get('next', None))

    if form.validate_on_submit():
        user, authenticated = User.authenticate(form.login.data,
                                    form.password.data)

        if user and authenticated:
            if login_user(user):
                flash("Logged in", 'success')
            return redirect(form.next.data or url_for('user.index'))
        else:
            flash('Sorry, invalid login', 'error')

    return render_template('frontend/login.html', form=form)

@frontend.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logged out', 'success')
    return redirect(url_for('frontend.index'))
    

loucloud/host/__init__.py
#!/usr/bin/env python
# encoding: utf-8

from .views import host

loucloud/host/views.py
#!/usr/bin/env python
# encoding: utf-8

from flask import Blueprint, render_template, request, redirect, url_for
from flask.ext.login import login_required
from .forms import AddHostForm
from .models import Host
from ..extensions import db
from ..decorators import admin_required

host = Blueprint('host', __name__, url_prefix='/hosts')

@host.route('/', methods=['GET', 'POST'])
@login_required
@admin_required
def index():
    if request.method == 'GET':
        form = AddHostForm()
        host_list = Host.query.filter().all()
        return render_template("host/index.html", form=form, host_list=host_list)

    else:
        form = AddHostForm(request.form)
        if form.validate_on_submit():
            host_instance = Host()
            form.populate_obj(host_instance)
            db.session.add(host_instance)
            db.session.commit()
        return redirect(url_for('host.index'))


@host.route('/<int:host_id>/delete', methods=['GET'])
@login_required
@admin_required
def delete_host(host_id):
    host_instance = Host.query.filter(Host.id==host_id).first()
    if host_instance:
        db.session.delete(host_instance)
        db.session.commit()
    return redirect(url_for('host.index'))

loucloud/image/__init__.py
#!/usr/bin/env python
# encoding: utf-8

from .views import image

loucloud/image/views.py
#!/usr/bin/env python
# encoding: utf-8

from flask import Blueprint, render_template, request, redirect, url_for
from flask.ext.login import login_required
# from .forms import AddHostForm
# from .models import Host
# from ..extensions import db
# from ..decorators import admin_required

image = Blueprint('image', __name__, url_prefix='/image')

@image.route('/', methods=['GET', 'POST'])
@login_required
@admin_required
def index():

    #list all images 
    return render_template("image/index.html")
#     if request.method == 'GET':
#         form = AddHostForm()
#         host_list = Host.query.filter().all()
#         return render_template("host/index.html", form=form, host_list=host_list)

#     else:
#         form = AddHostForm(request.form)
#         if form.validate_on_submit():
#             host_instance = Host()
#             form.populate_obj(host_instance)
#             db.session.add(host_instance)
#             db.session.commit()
#         return redirect(url_for('host.index'))


# @host.route('/<int:host_id>/delete', methods=['GET'])
# @login_required
# @admin_required
# def delete_host(host_id):
#     host_instance = Host.query.filter(Host.id==host_id).first()
#     if host_instance:
#         db.session.delete(host_instance)
#         db.session.commit()
#     return redirect(url_for('host.index'))
@image.route('/', methods=['GET', 'POST'])
@login_required
@admin_required
def add_image():

    return redirect(url_for('image.index'))



@image.route('/', methods=['GET', 'POST'])
@login_required
@admin_required
def delete_image():

    return redirect(url_for('image.index'))

loucloud/template/__init__.py
#!/usr/bin/env python
# encoding: utf-8

from .views import template

loucloud/template/views.py
#!/usr/bin/env python
# encoding: utf-8

from flask import Blueprint, render_template, request, redirect, url_for
from flask.ext.login import login_required
# from .forms import AddHostForm
# from .models import Host
# from ..extensions import db
# from ..decorators import admin_required

tempalte = Blueprint('template', __name__, url_prefix='/template')

@template.route('/', methods=['GET', 'POST'])
@login_required
@admin_required
def index():

    return render_template("template/index.html")
#     if request.method == 'GET':
#         form = AddHostForm()
#         host_list = Host.query.filter().all()
#         return render_template("host/index.html", form=form, host_list=host_list)

#     else:
#         form = AddHostForm(request.form)
#         if form.validate_on_submit():
#             host_instance = Host()
#             form.populate_obj(host_instance)
#             db.session.add(host_instance)
#             db.session.commit()
#         return redirect(url_for('host.index'))


# @host.route('/<int:host_id>/delete', methods=['GET'])
# @login_required
# @admin_required
# def delete_host(host_id):
#     host_instance = Host.query.filter(Host.id==host_id).first()
#     if host_instance:
#         db.session.delete(host_instance)
#         db.session.commit()
#     return redirect(url_for('host.index'))

loucloud/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>LouCloud</title>
	<script src="/static/js/jquery-1.11.3.min.js"></script>
	<script src="/static/js/index.js"></script>
	<script src="/static/bootstrap-3.3.5/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="/static/bootstrap-3.3.5/css/bootstrap.min.css">
</head>
<body style="padding-top: 20px; padding-bottom: 20px">
    {% block topbar %}
    <div class='container'>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{{ url_for('frontend.index') }}">LouCloud</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="/">Home</a></li>
                        {% if current_user.is_authenticated() %}
                        {% if current_user.is_admin() %}
                        <li><a href="{{ url_for('user.admin') }}">User</a></li>
                        <li><a href="{{ url_for('host.index') }}">Host</a></li>
                        <li><a href="/">Image</a></li>
                        <li><a href="/">Template</a></li>
                        {% endif %}
                        <li><a href="/">VirtualMachine</a></li>
                        {% endif %}
                        
                        <li><a href='https://www.shiyanlou.com/courses/354'>About</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated() %}
                        <li><a href="{{ url_for('user.index') }}">{{ current_user.name }}</a></li>
                        <li><a href="{{ url_for('frontend.logout') }}">Logout</a></li>
                    {% else %}
                        <li><a href="{{ url_for('frontend.login') }}">Login</a></li>
                    {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    {% endblock %}
    {% block flash_message %}
        <div class="container-fluid">
        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
            <div class="container-fluid">
                <div id='flash_message_container'>
                    {% for category, msg in messages %}
                        <div class="alert alert-{{ category }}">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            {{ msg }}
                        </div>
                    {% endfor %}
                </div>
            </div>
            {% endif %}
        {% endwith %}
        </div>
    {% endblock %}
    <div class="container">
    {% block body %}
    {% endblock %}
    </div>
</body>
</html>